module.exports = {
    GET_CHARACTERS : "GET_CHARACTERS",
    RECEIVE_CHARACTERS : "RECEIVE_CHARACTERS",
    SEND_CHARACTERS : "SEND_CHARACTERS",
    GET_CHARACTER : "GET_CHARACTER",
    RECEIVE_CHARACTER : "RECEIVE_CHARACTER",
    RECEIVE_PLOD_CHARACTERS : "RECEIVE_PLOD_CHARACTERS",
    SORT_FIELD_NAME: "name",
    SORT_FIELD_PLOD: "plod",
    SORT_FIELD_POPULARITY: "popularity",
    SORT_TYPE_ASC: 1,
    SORT_TYPE_DESC: -1
};
