module.exports = {
    GET_CHARACTERS : "GET_CHARACTERS",
    RECEIVE_CHARACTERS : "RECEIVE_CHARACTERS",
    SEND_CHARACTERS : "SEND_CHARACTERS",
    GET_CHARACTER : "GET_CHARACTER",
    RECEIVE_CHARACTER : "RECEIVE_CHARACTER",
    RECEIVE_PLOD_CHARACTERS : "RECEIVE_PLOD_CHARACTERS"
};
